### REGISTER USER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Rahul Sharma",
  "email": "rahul@example.com",
  "password": "123456"
}

###

### LOGIN USER
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "rahul@example.com",
  "password": "123456"
}



### GET SUBJECTS FOR A USER
GET http://localhost:5000/api/subjects/1
Content-Type: application/json

###

### ADD A NEW SUBJECT
POST http://localhost:5000/api/subjects
Content-Type: application/json

{
  "user_id": 1,
  "subject_name": "Physics"
}